# Generated by Django 5.1.7 on 2025-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
