# Generated by Django 5.1.7 on 2025-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckupbooking',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
