# Generated by Django 5.1.7 on 2025-04-30 11:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
