# Generated by Django 5.1.7 on 2025-03-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_healthcheckupbooking_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaypaymentdetails',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='core.healthcheckupbooking'),
        ),
    ]
