# Generated by Django 5.1.7 on 2025-03-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_razorpaypaymentdetails_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='department',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='department',
            name='speciality_type',
        ),
    ]
