# Generated by Django 5.1.7 on 2025-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_description_department_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
