# Generated by Django 5.1.7 on 2025-04-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_department_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='breadcamp',
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
