# Generated by Django 5.1.7 on 2025-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
