# Generated by Django 5.1.7 on 2025-03-13 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_status', models.BooleanField(default=False)),
                ('redirection_url', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(default='career', max_length=200)),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('is_alarmed', models.BooleanField(default=False)),
            ],
        ),
    ]
